version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "requirements/common.txt" }}-{{ checksum "requirements/dev.txt" }}
            - dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install -r requirements/dev.txt

      - save_cache:
          paths:
            - ~/venv
          key: dependencies-{{ checksum "requirements/common.txt" }}-{{ checksum "requirements/dev.txt" }}

      - run:
          name: test
          command: |
            . ~/venv/bin/activate
            ./scripts/test.sh


      - store_artifacts:
          path: test-reports
          destination: test-reports
